services:
  app:
    build:
      target: final

    user: ${USER_ID:-1000}
    ports:
      - "60000:8000"

    volumes: &app_volumes
      - ./staticfiles:/wd/staticfiles
      - ./media:/wd/media

    develop:
      watch:
        - action: sync
          path: ./manage.py
          target: /wd/manage.py
        - action: sync
          path: ./apps/
          target: /wd/apps/
        - action: sync
          path: ./core/
          target: /wd/core/

        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: .python-version

    # https://docs.docker.com/reference/compose-file/services/#init
    # https://github.com/krallin/tini
    # https://github.com/krallin/tini/issues/8
    init: true

  init:
    user: ${USER_ID:-1000}

    volumes: *app_volumes

  postgres:
    ports:
      - "5432:5432"

