# Generated by Django 5.2.1 on 2025-06-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField()),
                ("rating", models.FloatField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("calories", models.IntegerField(blank=True, null=True)),
                ("protein", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("carbohydrates", models.FloatField(blank=True, null=True)),
                ("cuisine", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Час приготування в хвилинах",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ingredients", models.ManyToManyField(to="base.ingredient")),
            ],
        ),
    ]
