# Generated by Django 5.2.1 on 2025-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Час приготування в хвилинах",
            ),
        ),
    ]
