# Generated by Django 5.2.1 on 2025-06-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="carbohydrates",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cuisine",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="fat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="protein",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
