# Generated by Django 5.2.1 on 2025-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="youtube_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
